### ISSUE TITLE
Interest in bumping nix to the latest version?

### ISSUE THREAD

**Issue by fasterthanlime** [bytecodealliance/userfaultfd-rs#40]
nix was bumped a few minor versions since December of 2022 - it's at 0.26.2 now.

Right now I have nix twice in my dependencies, one for me, one for userfaultfd. I'd love to upgrade userfaultfd's nix dependency to 0.26.x - is that something you'd be interested in merging or not?

**Comment by waywardmonkeys** [comment]
It looks like this could be closed now?
