### ISSUE TITLE
How to release a new version?

### ISSUE THREAD

**Issue by kawasin73** [bytecodealliance/userfaultfd-rs#46]
#45 bumped the `userfautlfd-sys` version.

@pchickey How we can release the new version to crate.io? Do you have any workflows or commands to publich? I will add a new wiki page for the workflow for other owners. Also I'd like to have the crate.io owner to publish.

**Comment by pchickey** [comment]
All that is required is to run `cargo publish` from the userfaultfd-sys crate's root directory. If you are not authenticated with crates.io, cargo publish will prompt you to login.

I have invited you to be an owner of userfaultfd and userfaultfd-sys on crates.io. I had already made your colleague hikalium an owner of userfaultfd and I added them to -sys as well.

**Comment by kawasin73** [comment]
Thanks! Published userfaultfd-sys 0.4.4 and wrote a simple page on wiki https://github.com/bytecodealliance/userfaultfd-rs/wiki
