### ISSUE TITLE
Using yanked version of nix

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [bytecodealliance/userfaultfd-rs#50]
The current version of nix used is yanked, this will fail `cargo audit` see https://buildkite.com/firecracker/firecracker-pr/builds/5724#018a40b3-6075-4a4f-b2b7-ecdb8726f631

The solution is for the version of nix to be updated.

This problem will occur again, this can be mitigated in the future by enabling [Dependabot](https://github.com/dependabot).

**Comment by pchickey** [comment]
Thanks for the report, I'll make a patch and a new release.

We have dependabot enabled for alerts and security updates, but not for version updates - these are the default settings. I'd expect that a yanked package would be a security update? Did dependabot pick this up this yanked dependency in other repos?

**Comment by JonathanWoollett-Light** [comment]
> Thanks for the report, I'll make a patch and a new release.
> 
> We have dependabot enabled for alerts and security updates, but not for version updates - these are the default settings. I'd expect that a yanked package would be a security update? Did dependabot pick this up this yanked dependency in other repos?

I am not aware of dependabot picking up the new release in other repo's where it is not enabled for version updates. I think for security updates it only cares about CVEs, in the case of nix I believe the yank is due to an error in the documentation and not a security bug.

**Comment by JonathanWoollett-Light** [comment]
Dependabot can be configured to group updates so as to avoid some of the noise.
